version: '3.8'
services:
  postgres-compose:
    image: postgis/postgis:13-3.2
    environment:
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network
  test-postgres-compose:
    image: postgis/postgis:13-3.2
    environment:
      POSTGRES_PASSWORD: "123"
    ports:
      - "5435:5435"
    networks:
      - postgres-compose-network
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgree"
    ports:
      - "15432:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network
  redis-compose:
    image: redis
    ports:
      - "6379:6379"
    networks: 
      - redis-network-compose
networks: 
  postgres-compose-network:
    driver: bridge
  redis-network-compose:
    driver: bridge